In [1]:
import pandas as pd

# 1. 대학 목록
- 전국 대학교 목록 조회
- 서울시 내 대학교로 제한

In [2]:
# https://www.data.go.kr/data/15100330/fileData.do
university = pd.read_excel('/Users/donghyunkim/Downloads/학교개황(20220310기준).xls')
university.head()

,학교구분,학교코드,학교명,본분교,학제,지역,설립구분,관련법령,법인명,학교상태,...,영문학교명,주소,영문주소,중문주소,우편번호,학교개교일,학교홈페이지,총장(대학원장)명,학교대표\r\n번호,학교대표\r\n팩스번호
0,대학,1,강릉원주대학교,본교,대학교,강원,국립,고등교육법,해당없음,기존,...,Gangneung Wonju National University,"강원도 강릉시 죽헌길 7 (지변동, 강릉원주대학교)","7, Jukheon-gil, Gangneung-si, Gangwon-do, Repu...","7, Jukheon-gil, Gangneung-si, Gangwon-do, Repu...",25457.0,1979-03-01,www.gwnu.ac.kr,반선섭,033-642-7001,033-643-7110
1,대학,2,강릉원주대학교,제2캠퍼스,대학교,강원,국립,고등교육법,해당없음,기존,...,Gangneung Wonju National University,"강원도 원주시 흥업면 남원로 150 (흥업리, 강릉원주대학교원주캠퍼스)","150, Namwon-ro, Heungeop-myeon, Wonju-si, Gang...","150, Namwon-ro, Heungeop-myeon, Wonju-si, Gang...",26403.0,2007-03-01,www.gwnu.ac.kr,반선섭,033-760-8020,033-760-8029
2,대학,3,강원대학교,본교,대학교,강원,국립,고등교육법,해당없음,기존,...,Kangwon National University,"강원도 춘천시 강원대학길 1 (효자동, 강원대학교)","1, Gangwondaehak-gil, Chuncheon-si, Gangwon-do...","1, Gangwondaehak-gil, Chuncheon-si, Gangwon-do...",24341.0,1970-03-01,www.kangwon.ac.kr/,김헌영,033-250-6114,033-251-9556
3,대학,4,강원대학교,제2캠퍼스,대학교,강원,국립,고등교육법,해당없음,기존,...,Kangwon National University,"강원도 삼척시 중앙로 346 (교동, 강원대학교삼척캠퍼스)","346, Jungang-ro, Samcheok-si, Gangwon-do, Repu...","346, Jungang-ro, Samcheok-si, Gangwon-do, Repu...",25913.0,2006-03-01,www.kangwon.ac.kr/,김헌영,033-570-6114,033-572-8620
4,대학,5,경북대학교,본교,대학교,대구,국립,고등교육법,해당없음,기존,...,Kyungpook National University,"대구광역시 북구 대학로 80 (산격동, 경북대학교)","80, Daehak-ro, Buk-gu, Daegu, Republic of Korea","80, Daehak-ro, Buk-gu, Daegu, Republic of Korea",41566.0,1946-05-28,www.knu.ac.kr,홍원화,053-950-5114,053-950-2149

In [3]:
# 서울 내 대학교, 전문대학교로 한정
university_seoul = university[((university['학교구분'] == '대학') | (university['학교구분'] == '전문대학')) & (university['지역'] == '서울')]
university_seoul = university_seoul.replace('케이씨대학교', '강서대학교')
university_seoul.head()

,학교구분,학교코드,학교명,본분교,학제,지역,설립구분,관련법령,법인명,학교상태,...,영문학교명,주소,영문주소,중문주소,우편번호,학교개교일,학교홈페이지,총장(대학원장)명,학교대표\r\n번호,학교대표\r\n팩스번호
13,대학,19,서울대학교,본교,대학교,서울,국립대법인,고등교육법,서울대학교 법인,기존,...,Seoul National University,"서울특별시 관악구 관악로 1 (신림동, 서울대학교)","1, Gwanak-ro, Gwanak-gu, Seoul, Republic of Korea","1, Gwanak-ro, Gwanak-gu, Seoul, Republic of Korea",8826.0,1946-08-22,www.snu.ac.kr,오세정,02-880-5114,02-885-5272
24,대학,32,한국체육대학교,본교,대학교,서울,국립,고등교육법,해당없음,기존,...,Korea National Sport University,"서울특별시 송파구 양재대로 1239 (방이동, 한국체육대학교)","1239, Yangjae-daero, Songpa-gu, Seoul, Republi...","1239, Yangjae-daero, Songpa-gu, Seoul, Republi...",5541.0,1976-12-30,www.knsu.ac.kr/,안용규,02-410-6700,02-418-1877
28,대학,36,서울과학기술대학교,본교,대학교,서울,국립,고등교육법,해당없음,기존,...,Seoul National University Of Science And Techn...,"서울특별시 노원구 공릉로 232 (공릉동, 서울과학기술대학교)","232, Gongneung-ro, Nowon-gu, Seoul, Republic o...","232, Gongneung-ro, Nowon-gu, Seoul, Republic o...",1811.0,2012-03-01,www.seoultech.ac.kr,이동훈,02-970-6114,02-970-6088
31,대학,40,서울시립대학교,본교,대학교,서울,공립,고등교육법,해당없음,기존,...,University Of Seoul,"서울특별시 동대문구 서울시립대로 163 (전농동, 서울시립대학교)","163, Seoulsiripdae-ro, Dongdaemun-gu, Seoul, R...","163, Seoulsiripdae-ro, Dongdaemun-gu, Seoul, R...",2504.0,1918-05-01,www.uos.ac.kr,서순탁,02-6490-6114,02-6490-6439
33,대학,48,가톨릭대학교,제2캠퍼스,대학교,서울,사립,고등교육법,가톨릭학원,기존,...,The Catholic University Of Korea,"서울특별시 서초구 반포대로 222 (반포동, 가톨릭대학교성의교정)","222, Banpo-daero, Seocho-gu, Seoul, Republic o...","222, Banpo-daero, Seocho-gu, Seoul, Republic o...",6591.0,1995-03-01,www.catholic.ac.kr,원종철,02-2258-7114,02-533-4362

# 2. 학생 목록
- 학교 및 캠퍼스별 학과 수, 학생 수 불러오기
- 재학생 수로 한정
- 학교 목록의 학교명, 캠퍼스명 통일 후 조인하여 파일 합치기

In [4]:
# https://kess.kedi.re.kr/contents/dataset
student = pd.read_excel('/Users/donghyunkim/Downloads/2023년 고등 학교별 학과수 입학정원 지원 입학 학생 외국인학생 졸업 교직.xlsx')
student.head()

,연도,학제,대학원구분,학교명,학교상태,본분교,시도,시군구,설립,주야구분,주소,우편번호,전화번호,팩스번호,홈페이지,재학생_전체_계,재학생_전체_남,재학생_전체_여
0,2023,대학교,NaN,서울대학교,기존,본교(제1캠퍼스),서울,서울 관악구,국립대법인,주간,"서울특별시 관악구 관악로 1 (신림동, 서울대학교)",8826,02-880-5114,02-885-5272,www.snu.ac.kr,15816,9492,6324
1,2023,대학교,NaN,서울대학교,기존,본교(제2캠퍼스),서울,서울 종로구,국립대법인,주간,서울 종로구 대학로 103,3080,02-880-5114,02-885-5272,www.snu.ac.kr,846,439,407
2,2023,일반대학원,부설대학원,서울대학교 대학원,기존,본교(제1캠퍼스),서울,서울 관악구,국립대법인,주간,"서울특별시 관악구 관악로 1 (신림동, 서울대학교)",8826,02-880-5114,02-885-5272,https://www.snu.ac.kr/academics/graduate/gradu...,8056,4244,3812
3,2023,일반대학원,부설대학원,서울대학교 일반대학원,기존,본교(제2캠퍼스),서울,서울 관악구,국립대법인,주간,서울 관악구 관악로 1,8826,02-880-5114,02-885-5272,https://www.snu.ac.kr/academics/graduate/gradu...,1308,544,764
4,2023,전문대학원,부설대학원,서울대학교 국제대학원,기존,본교(제1캠퍼스),서울,서울 관악구,국립대법인,주간,"서울특별시 관악구 관악로 1 (신림동, 서울대학교)",8826,02-880-8505,02-879-1496,gsis.snu.ac.kr,275,78,197

In [5]:
# 본분교명 수정
student = student.replace({'본교(제1캠퍼스)' : '본교', '본교(제2캠퍼스)' : '제2캠퍼스', '본교(제3캠퍼스)': '제3캠퍼스', '명지대학교 인문캠퍼스' : '명지대학교', 
                           '한국폴리텍대학 서울정수캠퍼스' : '한국폴리텍 I 대학 서울정수캠퍼스', '한국폴리텍대학 서울강서캠퍼스' : '한국폴리텍 I 대학 서울강서캠퍼스'})[['학교명', '본분교', '재학생_전체_계', '재학생_전체_남', '재학생_전체_여']]
university_seoul = pd.merge(left = university_seoul, right = student, how = 'left', on = ['학교명', '본분교'])

# 3. 학교 보유면적
- 대학교 별 보유면적 불러오기
- 학교 목록의 학교명, 캠퍼스명 통일 후 조인하여 파일 합치기
- 데이터셋에 없는 대학교는 따로 탐색하여 데이터 추가

In [6]:
# https://www.academyinfo.go.kr/uipnh/unt/unmcom/RdViewer.do
area = pd.read_excel('/Users/donghyunkim/Downloads/2022년_교육여건_교지+확보율.xls')
area

     번호  설립        학교명      캠퍼스명    학급    학종  지역  조사연도  보유면적(㎡)(C)
0    10  사립     가톨릭대학교     성신캠퍼스    대학  일반대학  서울  2022       51318
1    11  사립     가톨릭대학교     성의캠퍼스    대학  일반대학  서울  2022       86673
2    12  사립   감리교신학대학교    본교(서울)    대학  일반대학  서울  2022       24479
3    16  사립      강서대학교    본교(서울)    대학  일반대학  서울  2022       67033
4    19  사립      건국대학교    본교(서울)    대학  일반대학  서울  2022      455943
..  ...  ..        ...       ...   ...   ...  ..   ...         ...
74  405  사립  서울여자간호대학교  본교(서울홍제)  전문대학  일반대학  서울  2022        4534
75  407  사립      서일대학교        본교  전문대학  일반대학  서울  2022       29399
76  419  사립    숭의여자대학교    본교(서울)  전문대학  일반대학  서울  2022       25724
77  441  사립      인덕대학교    본교(서울)  전문대학  일반대학  서울  2022       76485
78  468  사립    한양여자대학교        본교  전문대학  일반대학  서울  2022       70558

[79 rows x 9 columns]

In [7]:
# 본분교명 수정
area.rename(columns = {'캠퍼스명' : '본분교', '보유면적(㎡)(C)' : '보유면적'}, inplace = True)
area['본분교'] = area['본분교'].str.split('(', expand = True)[0]
area = area.replace({'인문캠퍼스' : '본교', '성신캠퍼스' : '제3캠퍼스', '성의캠퍼스' : '제2캠퍼스', '쌍문캠퍼스' : '본교', 
                     '종로캠퍼스' : '제2캠퍼스', '인문사회과학캠퍼스' : '본교', '운정그린캠퍼스' : '제2캠퍼스'})
area = area[['학교명', '본분교', '보유면적']]

In [8]:
# 조인 및 사이버대학 제외, 기타 값 추가
university_seoul = pd.merge(left = university_seoul, right = area, how = 'left', on = ['학교명', '본분교'])
university_seoul.iloc[18, -1] = 55486 # 명지대학교
university_seoul = university_seoul[university_seoul['학제'] != '사이버대학(대학)']
university_seoul = university_seoul[university_seoul['학교명'] != '한국방송통신대학교']
university_seoul = university_seoul[university_seoul['학교명'] != '정석대학']
university_seoul.iloc[43, -1] = 143768 # 한국예술종합학교 https://academyinfo.go.kr/uipnh/unt/unmcom/RdViewer.do
university_seoul.iloc[-3, -1] = 25326 # 한국폴리텍 정수캠퍼스https://academyinfo.go.kr/uipnh/unt/unmcom/RdViewer.do
university_seoul.iloc[-2, -1] = 32403 # 한국폴리텍 강서캠퍼스 https://academyinfo.go.kr/uipnh/unt/unmcom/RdViewer.do

# 4. 도로명주소 -> 지번주소 변환
- 도로명주소 열을 분리하여 시, 구, 동, 지번주소로 변환
- 동별 학교 개수, 보유면적 합, 재학생 합 도출
- 법정동 코드 추가

In [9]:
address = university_seoul['주소'].str.split(' ', expand = True)
address.columns = ['시', '구', '로', '번', '동', '대', '기타']
address = address[['시', '구', '동']]
address['동'] = address['동'].str[1:-1]

In [10]:
university_seoul = pd.concat([university_seoul, address], axis = 1)
university_seoul['지번주소'] = university_seoul['시'] + " " + university_seoul['구'] + " " + university_seoul['동']
university_seoul.head()

,학교구분,학교코드,학교명,본분교,학제,지역,설립구분,관련법령,법인명,학교상태,...,학교대표\r\n번호,학교대표\r\n팩스번호,재학생_전체_계,재학생_전체_남,재학생_전체_여,보유면적,시,구,동,지번주소
0,대학,19,서울대학교,본교,대학교,서울,국립대법인,고등교육법,서울대학교 법인,기존,...,02-880-5114,02-885-5272,15816,9492,6324,4108394.0,서울특별시,관악구,신림동,서울특별시 관악구 신림동
1,대학,32,한국체육대학교,본교,대학교,서울,국립,고등교육법,해당없음,기존,...,02-410-6700,02-418-1877,2410,1544,866,111902.0,서울특별시,송파구,방이동,서울특별시 송파구 방이동
2,대학,36,서울과학기술대학교,본교,대학교,서울,국립,고등교육법,해당없음,기존,...,02-970-6114,02-970-6088,10115,6129,3986,504922.0,서울특별시,노원구,공릉동,서울특별시 노원구 공릉동
3,대학,40,서울시립대학교,본교,대학교,서울,공립,고등교육법,해당없음,기존,...,02-6490-6114,02-6490-6439,8697,5102,3595,434004.0,서울특별시,동대문구,전농동,서울특별시 동대문구 전농동
4,대학,48,가톨릭대학교,제2캠퍼스,대학교,서울,사립,고등교육법,가톨릭학원,기존,...,02-2258-7114,02-533-4362,903,447,456,86673.0,서울특별시,서초구,반포동,서울특별시 서초구 반포동

In [11]:
# 법정동 별 학교 개수, 보유면적 합, 재학생 합 구하기
dong = university_seoul.groupby('지번주소').agg({'학교명' : 'count', '보유면적' : 'sum', '재학생_전체_계' : 'sum'}).reset_index()

In [12]:
dong.head()

            지번주소  학교명       보유면적  재학생_전체_계
0  서울특별시 강서구 화곡동    2    99436.0      2141
1  서울특별시 관악구 신림동    1  4108394.0     15816
2  서울특별시 광진구 광장동    1    63090.0       616
3  서울특별시 광진구 군자동    1   120727.0     12414
4  서울특별시 광진구 화양동    1   455943.0     15688

In [13]:
# https://www.code.go.kr/stdcode/regCodeL.do
dong_code = pd.read_csv('/Users/donghyunkim/Downloads/법정동코드 전체자료.txt', encoding='cp949', sep='\t')
dong_code.head()

        법정동코드           법정동명 폐지여부
0  1100000000          서울특별시   존재
1  1111000000      서울특별시 종로구   존재
2  1111010100  서울특별시 종로구 청운동   존재
3  1111010200  서울특별시 종로구 신교동   존재
4  1111010300  서울특별시 종로구 궁정동   존재

In [14]:
# 법정동명이 서울특별시인 데이터만 조회
dong_code = dong_code[dong_code['법정동명'].str.split(' ', expand=True)[0] == '서울특별시']
dong_code.columns = ['법정동코드', '지번주소', '폐지여부']

In [15]:
dong_sum = pd.merge(left = dong, right = dong_code[['법정동코드', '지번주소']], how = 'left', on = '지번주소')
dong_sum

                지번주소  학교명       보유면적  재학생_전체_계       법정동코드
0      서울특별시 강서구 화곡동    2    99436.0      2141  1150010300
1      서울특별시 관악구 신림동    1  4108394.0     15816  1162010200
2      서울특별시 광진구 광장동    1    63090.0       616  1121510400
3      서울특별시 광진구 군자동    1   120727.0     12414  1121510900
4      서울특별시 광진구 화양동    1   455943.0     15688  1121510700
5      서울특별시 구로구 개봉동    1    18899.0       623  1153010700
6      서울특별시 구로구 고척동    1    36881.0      5783  1153010600
7       서울특별시 구로구 항동    1    39431.0      2038  1153011200
8      서울특별시 노원구 공릉동    3  1049479.0     22578  1135010300
9      서울특별시 노원구 상계동    1    18619.0      1014  1135010500
10     서울특별시 노원구 월계동    2   152321.0     14335  1135010200
11     서울특별시 도봉구 쌍문동    1   170742.0      5385  1132010500
12    서울특별시 동대문구 이문동    1    81199.0      9333  1123011000
13    서울특별시 동대문구 전농동    1   434004.0      8697  1123010400
14    서울특별시 동대문구 회기동    1   351547.0     14567  1123010800
15    서울특별시 동대문구 휘경동    1    49710.0      1265  1123010900
16     서울특별시 동작구 사당동    1    74694.0      1374  1159010700
17     서울특별시 동작구 상도동    1   133951.0     14411  1159010200
18     서울특별시 동작구 흑석동    1   151779.0     18742  1159010500
19     서울특별시 마포구 상수동    1   112653.0     12365  1144011500
20     서울특별시 마포구 신수동    1   208677.0      8100  1144011100
21   서울특별시 서대문구 남가좌동    1    55486.0      7674  1141012000
22    서울특별시 서대문구 냉천동    1    24479.0       604  1141010500
23    서울특별시 서대문구 대현동    1   545068.0     15503  1141011200
24   서울특별시 서대문구 북아현동    1    32681.0      1110  1141011000
25    서울특별시 서대문구 신촌동    1   828528.0     14787  1141011400
26  서울특별시 서대문구 충정로2가    1    19157.0      2103  1141010100
27    서울특별시 서대문구 홍은동    1    33500.0      6622  1141011800
28    서울특별시 서대문구 홍제동    1     4534.0       851  1141011100
29     서울특별시 서초구 반포동    1    86673.0       903  1165010700
30     서울특별시 서초구 서초동    1    82662.0      1444  1165010800
31     서울특별시 성동구 사근동    2   472287.0     23529  1120010600
32     서울특별시 성북구 돈암동    1   101874.0      6587  1129010300
33   서울특별시 성북구 삼선동2가    1    48726.0      6942  1129011200
34     서울특별시 성북구 석관동    1   143768.0      1797  1129013900
35   서울특별시 성북구 안암동5가    1   881440.0     20373  1129012500
36     서울특별시 성북구 정릉동    2   245351.0     21459  1129013300
37    서울특별시 성북구 하월곡동    1    54323.0      6981  1129013600
38     서울특별시 송파구 방이동    1   111902.0      2410  1171011100
39     서울특별시 용산구 보광동    1    25326.0      1158  1117013600
40   서울특별시 용산구 청파동2가    1    68334.0     10348  1117011000
41     서울특별시 은평구 신사동    1     7940.0       413  1138010900
42    서울특별시 종로구 명륜3가    1   140983.0     11155  1111017300
43     서울특별시 종로구 필운동    1    23389.0      2741  1111011300
44     서울특별시 종로구 혜화동    1    51318.0       200  1111016900
45     서울특별시 종로구 홍지동    1   160005.0      6322  1111018500
46      서울특별시 중구 예장동    1    25724.0      3059  1114014200
47    서울특별시 중구 장충동2가    1   169649.0     12569  1114014400
48     서울특별시 중랑구 면목동    1    29399.0      5939  1126010100