In [1]:
#필요 라이브러리 import
import numpy as np
import pandas as pd

In [3]:
#휴게음식점 데이터 불러오기
df1 = pd.read_csv('휴게음식점.csv', encoding='cp949')
df1.shape

/var/folders/jc/q2j97l_x5hb7jh99pn7nsbym0000gn/T/ipykernel_75663/1310492345.py:2: DtypeWarning: Columns (11,39,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('휴게음식점.csv', encoding='cp949')

(550150, 48)

In [4]:
#일반음식점 데이터 불러오기
df2 = pd.read_csv('일반음식점.csv', encoding='cp949')
df2.shape

/var/folders/jc/q2j97l_x5hb7jh99pn7nsbym0000gn/T/ipykernel_75663/2418469537.py:2: DtypeWarning: Columns (11,27,39,41,44,45) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('일반음식점.csv', encoding='cp949')

(2105706, 48)

## 2. 데이터 살펴보기

- 사용할 변수 확인
- 추출해야할 카테고리 확인

In [5]:
#열(속성)확인하기(df1, df2는 같은 형식으로 작성되어 있음)
df1.columns

Index(['번호', '개방서비스명', '개방서비스아이디', '개방자치단체코드', '관리번호', '인허가일자', '인허가취소일자',
       '영업상태구분코드', '영업상태명', '상세영업상태코드', '상세영업상태명', '폐업일자', '휴업시작일자', '휴업종료일자',
       '재개업일자', '소재지전화', '소재지면적', '소재지우편번호', '소재지전체주소', '도로명전체주소', '도로명우편번호',
       '사업장명', '최종수정시점', '데이터갱신구분', '데이터갱신일자', '업태구분명', '좌표정보(x)', '좌표정보(y)',
       '위생업태명', '남성종사자수', '여성종사자수', '영업장주변구분명', '등급구분명', '급수시설구분명', '총직원수',
       '본사직원수', '공장사무직직원수', '공장판매직직원수', '공장생산직직원수', '건물소유구분명', '보증액', '월세액',
       '다중이용업소여부', '시설총규모', '전통업소지정번호', '전통업소주된음식', '홈페이지', 'Unnamed: 47'],
      dtype='object')

In [6]:
#df1의 업태구문명이 무엇이 얼마나 있는지 확인
df1['위생업태명'].value_counts()

위생업태명
커피숍         162542
기타 휴게음식점     92095
일반조리판매       86761
다방           79598
편의점          51228
패스트푸드        30685
과자점          23429
백화점           6616
푸드트럭          6223
전통찻집          2693
아이스크림         2633
키즈카페          1287
고속도로          1245
떡카페           1081
철도역구내          753
유원지            682
관광호텔           250
극장             212
공항              84
한식              11
분식               8
기타               4
김밥(도시락)          2
호프/통닭            2
룸살롱              1
식품소분업            1
까페               1
경양식              1
식육(숯불구이)         1
단란주점             1
Name: count, dtype: int64

In [7]:
#df2의 업태구문명이 무엇이 얼마나 있는지 확인
df2['위생업태명'].value_counts()

위생업태명
한식                 967555
기타                 228009
호프/통닭              202207
분식                 178829
경양식                119819
식육(숯불구이)            68535
중국식                 68131
통닭(치킨)              55049
일식                  51962
정종/대포집/소주방          43918
횟집                  31038
까페                  22160
패스트푸드               18734
뷔페식                 10393
탕류(보신용)             10029
김밥(도시락)              9094
외국음식전문점(인도,태국등)      7988
전통찻집                 2278
라이브카페                1582
패밀리레스트랑              1580
냉면집                  1453
복어취급                 1433
출장조리                 1120
감성주점                 1088
이동조리                  904
키즈카페                  628
일반조리판매                  9
기타 휴게음식점                7
커피숍                     6
간이주점                    4
다방                      2
식품소분업                   1
제과점영업                   1
식품등 수입판매업               1
룸살롱                     1
Name: count, dtype: int64

- 사용할 속성
    - 사업장명
    - 영업상태명
    - 인허가일자
    - 폐업일자
    - 소재지면적
    - 소재지전체주소
    - 위생업태명
- df1에서 추출한 업태구문명
    - 커피숍
    - 다방
    - 전통찻집
    - 떡카페
    - 까페
- df2에서 추출한 업태구분명
    - 까페
    - 전통찻집
    - 커피숍
    - 다방

## 3. 데이터 전처리
    1. df1에서 필요한 카테고리 내 데이터만 추출
    2. df1_cafe에서 서울에 존재하는 데이터만 추출
    2. df2의 '기타'에서 커피숍 추출하기

### (1) df1 전처리

In [106]:
#df1에서 커피전문점 데이터만 추출하기
df1_cafe = df1[(df1['위생업태명'] == '커피숍') | (df1['위생업태명'] == '다방') | (df1['위생업태명'] == '전통찻집') | (df1['위생업태명'] == '떡카페') | (df1['위생업태명'] == '까페')]
df1_cafe = df1_cafe[['사업장명','영업상태명', '인허가일자', '폐업일자', '소재지면적','소재지전체주소', '위생업태명', '개방자치단체코드']]
df1_cafe

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
6,덕소낙원떡집,폐업,2023-09-21,2023-09-22,39.90,경기도 남양주시 와부읍 덕소리 488-4,떡카페,3990000
19,카페지와이(고고마켓),폐업,2023-09-22,2023-09-24,NaN,울산광역시 중구 태화동 667 태화강 국가정원 안내센터,커피숍,3690000
44,위드고,폐업,2023-09-22,2023-10-08,NaN,서울특별시 노원구 상계동 713 롯데백화점,커피숍,3100000
49,쿠키앤모어,폐업,2023-09-22,2023-10-21,3.30,경기도 화성시 반송동 96 메타폴리스,커피숍,5530000
51,(주)제이와이에스유통,폐업,2023-09-22,2023-10-12,6.60,경기도 고양시 일산동구 장항동 784 롯데백화점일산점,커피숍,3940000
...,...,...,...,...,...,...,...,...
550134,스타벅스동대구터미널점,영업/정상,2011-08-11,NaN,252.00,"대구광역시 동구 신천동 330-6 번지외1필지 보광빌딩 가동 1,2층",커피숍,3420000
550135,메가엠지씨커피 광주봉선유안공원점,영업/정상,2008-08-14,NaN,65.00,광주광역시 남구 봉선동 138-2 (1층)103호,커피숍,3610000
550138,파운데이 염주점,영업/정상,2010-05-28,NaN,125.74,광주광역시 서구 화정동 824-17 (1층),커피숍,3600000
550141,벌크커피봉선점,영업/정상,2017-10-23,NaN,35.00,광주광역시 남구 봉선동 606번지 남양휴턴1차 106동 107호,커피숍,3610000
550144,파운데이 풍암점,영업/정상,2009-08-31,NaN,85.80,광주광역시 서구 풍암동 1117-6 (일층),커피숍,3600000

In [107]:
#df1_cafe 소재지 결측이 있는 데이터 제거
df1_cafe2 = df1_cafe.dropna(subset=['소재지전체주소'], how='any', axis=0)

In [108]:
#df1_cafe2에서 서울특별시에 위치하는 데이터 추출
total_cafe1 = df1_cafe2[df1_cafe2['소재지전체주소'].str.contains('서울특별시')]
total_cafe1

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
44,위드고,폐업,2023-09-22,2023-10-08,NaN,서울특별시 노원구 상계동 713 롯데백화점,커피숍,3100000
244,텐퍼센트커피(Tenpercent coffee),폐업,2023-09-18,2023-09-25,53.00,서울특별시 노원구 공릉동 567-4,커피숍,3100000
305,커피크루,폐업,2023-09-27,2023-10-06,NaN,서울특별시 서초구 양재동 232 AT센터,커피숍,3210000
309,마이빈(한시적),폐업,2023-10-06,2023-10-18,NaN,서울특별시 강남구 삼성동 159 코엑스,커피숍,3220000
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000
...,...,...,...,...,...,...,...,...
541185,굿애프터눈 합정점,영업/정상,2017-04-10,NaN,50.42,서울특별시 마포구 합정동 473 마포한강2차푸르지오상업시설 120호,커피숍,3130000
541187,보노보나마포합정점,영업/정상,2017-04-18,NaN,41.53,서울특별시 마포구 합정동 473번지,커피숍,3130000
541188,셀렉토커피 상암누리꿈스퀘어점,영업/정상,2017-04-14,NaN,43.76,서울특별시 마포구 상암동 1605 누리꿈스퀘어 지하1층 B1087호,커피숍,3130000
541190,로벤,영업/정상,2016-11-18,NaN,23.00,서울특별시 마포구 서교동 368-11번지,커피숍,3130000
543021,카페it수다,영업/정상,2020-08-03,NaN,33.00,서울특별시 서초구 방배동 451-32 1층,커피숍,3210000

In [109]:
#사업장명에 (한시적)인 변수 확인
delete_limited1 = total_cafe1[total_cafe1['사업장명'].str.contains('(한시적)')]
delete_limited1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 122 entries, 309 to 348794
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   사업장명      122 non-null    object
 1   영업상태명     122 non-null    object
 2   인허가일자     122 non-null    object
 3   폐업일자      119 non-null    object
 4   소재지면적     30 non-null     float64
 5   소재지전체주소   122 non-null    object
 6   위생업태명     122 non-null    object
 7   개방자치단체코드  122 non-null    int64
dtypes: float64(1), int64(1), object(6)
memory usage: 8.6+ KB

/var/folders/jc/q2j97l_x5hb7jh99pn7nsbym0000gn/T/ipykernel_75663/920330481.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  delete_limited1 = total_cafe1[total_cafe1['사업장명'].str.contains('(한시적)')]

In [110]:
#사업장명에 (한시적)인 변수 제거
total_cafe11 = total_cafe1.copy()
total_cafe11.drop(total_cafe11[total_cafe11['사업장명'].str.contains('(한시적)')].index, inplace=True)
total_cafe11

/var/folders/jc/q2j97l_x5hb7jh99pn7nsbym0000gn/T/ipykernel_75663/4258378861.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  total_cafe11.drop(total_cafe11[total_cafe11['사업장명'].str.contains('(한시적)')].index, inplace=True)

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
44,위드고,폐업,2023-09-22,2023-10-08,NaN,서울특별시 노원구 상계동 713 롯데백화점,커피숍,3100000
244,텐퍼센트커피(Tenpercent coffee),폐업,2023-09-18,2023-09-25,53.00,서울특별시 노원구 공릉동 567-4,커피숍,3100000
305,커피크루,폐업,2023-09-27,2023-10-06,NaN,서울특별시 서초구 양재동 232 AT센터,커피숍,3210000
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000
766,트래쉬버스터즈 스낵바,폐업,2023-10-12,2023-10-26,36.00,서울특별시 강남구 대치동 514 SETEC,커피숍,3220000
...,...,...,...,...,...,...,...,...
541185,굿애프터눈 합정점,영업/정상,2017-04-10,NaN,50.42,서울특별시 마포구 합정동 473 마포한강2차푸르지오상업시설 120호,커피숍,3130000
541187,보노보나마포합정점,영업/정상,2017-04-18,NaN,41.53,서울특별시 마포구 합정동 473번지,커피숍,3130000
541188,셀렉토커피 상암누리꿈스퀘어점,영업/정상,2017-04-14,NaN,43.76,서울특별시 마포구 상암동 1605 누리꿈스퀘어 지하1층 B1087호,커피숍,3130000
541190,로벤,영업/정상,2016-11-18,NaN,23.00,서울특별시 마포구 서교동 368-11번지,커피숍,3130000
543021,카페it수다,영업/정상,2020-08-03,NaN,33.00,서울특별시 서초구 방배동 451-32 1층,커피숍,3210000

In [111]:
#total_cafe11 면적 결측이 있는 데이터 제거
total_cafe12 = total_cafe11.dropna(subset=['소재지면적'], how='any', axis=0)
total_cafe12

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
244,텐퍼센트커피(Tenpercent coffee),폐업,2023-09-18,2023-09-25,53.00,서울특별시 노원구 공릉동 567-4,커피숍,3100000
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000
766,트래쉬버스터즈 스낵바,폐업,2023-10-12,2023-10-26,36.00,서울특별시 강남구 대치동 514 SETEC,커피숍,3220000
1047,카라멜리에오,폐업,2023-10-26,2023-10-31,12.23,서울특별시 강남구 압구정동 429 현대백화점본점,커피숍,3220000
1091,담은,폐업,2023-09-14,2023-10-24,56.00,서울특별시 강남구 도곡동 419-6,커피숍,3220000
...,...,...,...,...,...,...,...,...
541185,굿애프터눈 합정점,영업/정상,2017-04-10,NaN,50.42,서울특별시 마포구 합정동 473 마포한강2차푸르지오상업시설 120호,커피숍,3130000
541187,보노보나마포합정점,영업/정상,2017-04-18,NaN,41.53,서울특별시 마포구 합정동 473번지,커피숍,3130000
541188,셀렉토커피 상암누리꿈스퀘어점,영업/정상,2017-04-14,NaN,43.76,서울특별시 마포구 상암동 1605 누리꿈스퀘어 지하1층 B1087호,커피숍,3130000
541190,로벤,영업/정상,2016-11-18,NaN,23.00,서울특별시 마포구 서교동 368-11번지,커피숍,3130000
543021,카페it수다,영업/정상,2020-08-03,NaN,33.00,서울특별시 서초구 방배동 451-32 1층,커피숍,3210000

In [112]:
total_cafe_check1 = total_cafe12[(total_cafe12['사업장명'].str.contains('맥주')) | (total_cafe12['사업장명'].str.contains('주점'))| (total_cafe12['사업장명'].str.contains('호프'))| (total_cafe12['사업장명'].str.contains('펍'))| (total_cafe12['사업장명'].str.contains('맥주'))| (total_cafe12['사업장명'].str.contains('치킨'))| (total_cafe12['사업장명'].str.contains('스시')) | (total_cafe12['사업장명'].str.contains('국수'))| (total_cafe12['사업장명'].str.contains('만두'))| (total_cafe12['사업장명'].str.contains('닭'))| (total_cafe12['사업장명'].str.contains('떡볶이'))| (total_cafe12['사업장명'].str.contains('김밥'))| (total_cafe12['사업장명'].str.contains('족발'))| (total_cafe12['사업장명'].str.contains('죽'))].index
total_cafe_check1

Index([  9222,   9525,  41725,  42218,  43413,  44486,  46104,  47430,  48975,
        49507,  50774,  54010,  56615,  92264,  93999,  98047,  98788, 123157,
       130049, 132376, 151858, 152310, 153456, 153827, 154879, 156291, 157725,
       157766, 159371, 162382, 162467, 164868, 166342, 167851, 171935, 173288,
       173612, 211984, 215460, 217028, 223888, 224177, 224337, 226606, 233324,
       260862, 263311, 266006, 267004, 267211, 267352, 268290, 268326, 268481,
       270876, 272335, 272908, 273607, 273802, 353068, 355495, 377642, 385989,
       408666, 422074, 438611, 445354, 448227, 448444, 448967, 455338, 467660,
       468423, 469042, 470009, 470630, 471840, 490981, 504946, 511463, 512842,
       513093, 520011, 520911, 540986],
      dtype='int64')

In [113]:
#이상 데이터 삭제
df_cafe_1 = total_cafe12.copy()
df_cafe_1.drop(total_cafe_check1, inplace=True)
df_cafe_1

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
244,텐퍼센트커피(Tenpercent coffee),폐업,2023-09-18,2023-09-25,53.00,서울특별시 노원구 공릉동 567-4,커피숍,3100000
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000
766,트래쉬버스터즈 스낵바,폐업,2023-10-12,2023-10-26,36.00,서울특별시 강남구 대치동 514 SETEC,커피숍,3220000
1047,카라멜리에오,폐업,2023-10-26,2023-10-31,12.23,서울특별시 강남구 압구정동 429 현대백화점본점,커피숍,3220000
1091,담은,폐업,2023-09-14,2023-10-24,56.00,서울특별시 강남구 도곡동 419-6,커피숍,3220000
...,...,...,...,...,...,...,...,...
541185,굿애프터눈 합정점,영업/정상,2017-04-10,NaN,50.42,서울특별시 마포구 합정동 473 마포한강2차푸르지오상업시설 120호,커피숍,3130000
541187,보노보나마포합정점,영업/정상,2017-04-18,NaN,41.53,서울특별시 마포구 합정동 473번지,커피숍,3130000
541188,셀렉토커피 상암누리꿈스퀘어점,영업/정상,2017-04-14,NaN,43.76,서울특별시 마포구 상암동 1605 누리꿈스퀘어 지하1층 B1087호,커피숍,3130000
541190,로벤,영업/정상,2016-11-18,NaN,23.00,서울특별시 마포구 서교동 368-11번지,커피숍,3130000
543021,카페it수다,영업/정상,2020-08-03,NaN,33.00,서울특별시 서초구 방배동 451-32 1층,커피숍,3210000

### (2) df2 전처리

In [114]:
#df1에서 커피전문점 데이터만 추출하기(기타 제외)
df2_cafe = df2[(df2['위생업태명'] == '까페') | (df2['위생업태명'] == '전통찻집') | (df2['위생업태명'] == '커피숍') | (df2['위생업태명'] == '다방')]
df2_cafe = df2_cafe[['사업장명','영업상태명', '인허가일자', '폐업일자', '소재지면적','소재지전체주소', '위생업태명', '개방자치단체코드']]
df2_cafe

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
591,시청역,폐업,2023-10-18,2023-10-22,NaN,충청남도 논산시 강경읍 황산리 198,까페,4540000
2259,미엔,폐업,2005-07-04,2023-09-25,34.00,대구광역시 달서구 상인동 1419-6,까페,3470000
4100,벤티,폐업,2011-03-25,2023-06-30,85.00,전라남도 곡성군 곡성읍 읍내리 327-1,까페,4860000
6279,홍익까페,폐업,2015-03-31,2022-12-12,34.99,경상북도 포항시 북구 죽도동 44-10,까페,5020000
8006,나이스웨더 AK분당점,폐업,2020-11-27,2022-07-15,13.96,경기도 성남시 분당구 서현동 263 AK플라자 1층 일부,까페,3780000
...,...,...,...,...,...,...,...,...
2105259,옴서감서,영업/정상,1992-03-13,NaN,22.00,광주광역시 남구 주월동 1278-4번지 (일층),전통찻집,3610000
2105369,카메,영업/정상,2010-09-29,NaN,78.00,광주광역시 남구 봉선동 107-13 (1층),까페,3610000
2105608,투썸플레이스광주월곡점,영업/정상,1992-10-13,NaN,375.20,광주광역시 광산구 월곡동 313-4,까페,3630000
2105646,카페515(cafe 515),영업/정상,2013-02-20,NaN,64.13,광주광역시 남구 양림동 72-3 (1층),까페,3610000
2105690,솔리데오,영업/정상,2015-02-16,NaN,79.46,광주광역시 남구 백운동 597-5번지,까페,3610000

In [115]:
#df2_cafe 소재지 결측이 있는 데이터 제거
df2_cafe2 = df2_cafe.dropna(subset=['소재지전체주소'], how='any', axis=0)
df2_cafe2

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
591,시청역,폐업,2023-10-18,2023-10-22,NaN,충청남도 논산시 강경읍 황산리 198,까페,4540000
2259,미엔,폐업,2005-07-04,2023-09-25,34.00,대구광역시 달서구 상인동 1419-6,까페,3470000
4100,벤티,폐업,2011-03-25,2023-06-30,85.00,전라남도 곡성군 곡성읍 읍내리 327-1,까페,4860000
6279,홍익까페,폐업,2015-03-31,2022-12-12,34.99,경상북도 포항시 북구 죽도동 44-10,까페,5020000
8006,나이스웨더 AK분당점,폐업,2020-11-27,2022-07-15,13.96,경기도 성남시 분당구 서현동 263 AK플라자 1층 일부,까페,3780000
...,...,...,...,...,...,...,...,...
2105259,옴서감서,영업/정상,1992-03-13,NaN,22.00,광주광역시 남구 주월동 1278-4번지 (일층),전통찻집,3610000
2105369,카메,영업/정상,2010-09-29,NaN,78.00,광주광역시 남구 봉선동 107-13 (1층),까페,3610000
2105608,투썸플레이스광주월곡점,영업/정상,1992-10-13,NaN,375.20,광주광역시 광산구 월곡동 313-4,까페,3630000
2105646,카페515(cafe 515),영업/정상,2013-02-20,NaN,64.13,광주광역시 남구 양림동 72-3 (1층),까페,3610000
2105690,솔리데오,영업/정상,2015-02-16,NaN,79.46,광주광역시 남구 백운동 597-5번지,까페,3610000

In [116]:
#df1_cafe2에서 서울특별시에 위치하는 데이터 추출
total_cafe2 = df2_cafe2[df2_cafe2['소재지전체주소'].str.contains('서울특별시')]
total_cafe2

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
10031,바론,폐업,2015-02-04,2020-02-28,19.00,서울특별시 구로구 개봉동 139-20번지,까페,3160000
13504,럼프슈가(Lump Sugar),폐업,2014-10-24,2020-02-07,30.00,서울특별시 동대문구 이문동 264-167번지 1층,까페,3050000
13505,멜팅,폐업,2014-10-23,2016-11-07,10.80,서울특별시 동대문구 답십리동 178번지 래미안위브 1층 상가동 2-6호,까페,3050000
13759,이빠이,폐업,1999-12-03,2005-05-20,46.40,서울특별시 마포구 서교동 361-10번지,까페,3130000
13812,데일리,폐업,2014-11-24,2018-01-05,30.00,서울특별시 동대문구 장안동 216-32번지 1층,까페,3050000
...,...,...,...,...,...,...,...,...
2061332,갈채,영업/정상,1986-04-25,NaN,19.89,서울특별시 성북구 석관동 71-8,까페,3070000
2061422,블루씨티,영업/정상,2001-05-23,NaN,85.80,서울특별시 은평구 응암동 84-32 지하1층,까페,3110000
2061463,예스호프,영업/정상,2007-04-05,NaN,26.00,서울특별시 양천구 신월동 237-20 1층,까페,3140000
2061469,유토피아 카페,영업/정상,2014-10-30,NaN,167.32,서울특별시 은평구 갈현동 454-3번지 2층,까페,3110000
2061604,꽃샘,영업/정상,1983-07-19,NaN,20.80,서울특별시 성북구 길음동 1257-2번지,까페,3070000

In [117]:
#사업장명에 (한시적)인 변수 확인
delete_limited2 = total_cafe2[total_cafe2['사업장명'].str.contains('한시적')]
delete_limited2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   사업장명      0 non-null      object
 1   영업상태명     0 non-null      object
 2   인허가일자     0 non-null      object
 3   폐업일자      0 non-null      object
 4   소재지면적     0 non-null      float64
 5   소재지전체주소   0 non-null      object
 6   위생업태명     0 non-null      object
 7   개방자치단체코드  0 non-null      int64
dtypes: float64(1), int64(1), object(6)
memory usage: 0.0+ bytes

In [118]:
total_cafe_check2 = total_cafe2[(total_cafe2['사업장명'].str.contains('맥주')) | (total_cafe2['사업장명'].str.contains('주점'))| (total_cafe2['사업장명'].str.contains('호프'))| (total_cafe2['사업장명'].str.contains('펍'))| (total_cafe2['사업장명'].str.contains('치킨'))| (total_cafe2['사업장명'].str.contains('스시'))| (total_cafe2['사업장명'].str.contains('국수'))| (total_cafe2['사업장명'].str.contains('만두'))| (total_cafe2['사업장명'].str.contains('닭'))| (total_cafe2['사업장명'].str.contains('떢볶이'))| (total_cafe2['사업장명'].str.contains('족발')) | (total_cafe2['사업장명'].str.contains('김밥'))| (total_cafe2['사업장명'].str.contains('죽'))].index
total_cafe_check2

Index([  13855,   16463,   16768,   16960,  140339,  141338,  141673,  141789,
        142642,  144772,
       ...
       1932847, 1932978, 1933620, 1933869, 1934248, 1934664, 1943802, 1999944,
       2001375, 2061463],
      dtype='int64', length=156)

#이상 데이터 삭제하기
- '맥주', '주점', '호프', '펍', '치킨', '스시', '국수', '만두', '닭', '떡볶이', '족발', '김밥', '죽', '면'

In [119]:
#이상뎅터 삭제
df_cafe_2 = total_cafe2.copy()
df_cafe_2.drop(total_cafe_check2, inplace=True)
df_cafe_2

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
10031,바론,폐업,2015-02-04,2020-02-28,19.00,서울특별시 구로구 개봉동 139-20번지,까페,3160000
13504,럼프슈가(Lump Sugar),폐업,2014-10-24,2020-02-07,30.00,서울특별시 동대문구 이문동 264-167번지 1층,까페,3050000
13505,멜팅,폐업,2014-10-23,2016-11-07,10.80,서울특별시 동대문구 답십리동 178번지 래미안위브 1층 상가동 2-6호,까페,3050000
13759,이빠이,폐업,1999-12-03,2005-05-20,46.40,서울특별시 마포구 서교동 361-10번지,까페,3130000
13812,데일리,폐업,2014-11-24,2018-01-05,30.00,서울특별시 동대문구 장안동 216-32번지 1층,까페,3050000
...,...,...,...,...,...,...,...,...
2061319,구할 구,영업/정상,1970-10-14,NaN,98.66,서울특별시 중구 남산동2가 24-13 (1층2층),까페,3010000
2061332,갈채,영업/정상,1986-04-25,NaN,19.89,서울특별시 성북구 석관동 71-8,까페,3070000
2061422,블루씨티,영업/정상,2001-05-23,NaN,85.80,서울특별시 은평구 응암동 84-32 지하1층,까페,3110000
2061469,유토피아 카페,영업/정상,2014-10-30,NaN,167.32,서울특별시 은평구 갈현동 454-3번지 2층,까페,3110000
2061604,꽃샘,영업/정상,1983-07-19,NaN,20.80,서울특별시 성북구 길음동 1257-2번지,까페,3070000

### (3) 데이터 합치기

In [120]:
total_cafe_df = pd.concat([df_cafe_1, df_cafe_2])
total_cafe_df

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드
244,텐퍼센트커피(Tenpercent coffee),폐업,2023-09-18,2023-09-25,53.00,서울특별시 노원구 공릉동 567-4,커피숍,3100000
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000
766,트래쉬버스터즈 스낵바,폐업,2023-10-12,2023-10-26,36.00,서울특별시 강남구 대치동 514 SETEC,커피숍,3220000
1047,카라멜리에오,폐업,2023-10-26,2023-10-31,12.23,서울특별시 강남구 압구정동 429 현대백화점본점,커피숍,3220000
1091,담은,폐업,2023-09-14,2023-10-24,56.00,서울특별시 강남구 도곡동 419-6,커피숍,3220000
...,...,...,...,...,...,...,...,...
2061319,구할 구,영업/정상,1970-10-14,NaN,98.66,서울특별시 중구 남산동2가 24-13 (1층2층),까페,3010000
2061332,갈채,영업/정상,1986-04-25,NaN,19.89,서울특별시 성북구 석관동 71-8,까페,3070000
2061422,블루씨티,영업/정상,2001-05-23,NaN,85.80,서울특별시 은평구 응암동 84-32 지하1층,까페,3110000
2061469,유토피아 카페,영업/정상,2014-10-30,NaN,167.32,서울특별시 은평구 갈현동 454-3번지 2층,까페,3110000
2061604,꽃샘,영업/정상,1983-07-19,NaN,20.80,서울특별시 성북구 길음동 1257-2번지,까페,3070000

### (4) 프랜차이즈 구분
논문을 인용해 공정거래위원회 가맹사업거래사이트에서 정보공개서 비교정보를 이용해 서울에 직영점 또는 가맹점/직영점이 30개 이상 있는 프랜차이즈를 검색했고 직영점위주로 가맹사업거래사이트에서 검색되지 않는 대형 프랜차이즈도 포함시켜 총 n개의 사업체를 프랜차이즈로 처리하기로 결정했다. 

- 이디야커피
- 메가엠지씨커피
- 투썸플레이스
- 컴포즈커피
- 빽다방
- 더벤티
- 커피베이
- 커피에 반하다
- 요거프레소
- 파스쿠찌
- 할리스/할리스커피
- 엔제리너스
- 디저트39
- 탐앤탐스커피
- 매머드
- 감성커피
- 달리는커피
- 카페베네
- 셀렉토커피
- 토프레소
- 더카페 !!
- 아마스빈
- 만랩커피
- 더치앤빈
- 카페게이트
- 달.콤
- 커피사피엔스
- 커스텀커피
- 커피나무
- 커피빈(70)
- 스타벅스(611)
- 아티제(53)
- 폴바셋(64)
- 커피스미스(44)

In [125]:
#프랜차이즈여부 변수 생성 1 : 프랜차이즈, 0 : 독립
total_cafe_df['프랜차이즈'] = 0
total_cafe_df

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드,시군구,프랜차이즈
244,텐퍼센트커피(Tenpercent coffee),폐업,2023-09-18,2023-09-25,53.00,서울특별시 노원구 공릉동 567-4,커피숍,3100000,"[서울특별시, 노원구]",0
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000,"[서울특별시, 영등포구]",0
766,트래쉬버스터즈 스낵바,폐업,2023-10-12,2023-10-26,36.00,서울특별시 강남구 대치동 514 SETEC,커피숍,3220000,"[서울특별시, 강남구]",0
1047,카라멜리에오,폐업,2023-10-26,2023-10-31,12.23,서울특별시 강남구 압구정동 429 현대백화점본점,커피숍,3220000,"[서울특별시, 강남구]",0
1091,담은,폐업,2023-09-14,2023-10-24,56.00,서울특별시 강남구 도곡동 419-6,커피숍,3220000,"[서울특별시, 강남구]",0
...,...,...,...,...,...,...,...,...,...,...
2061319,구할 구,영업/정상,1970-10-14,NaN,98.66,서울특별시 중구 남산동2가 24-13 (1층2층),까페,3010000,"[서울특별시, 중구]",0
2061332,갈채,영업/정상,1986-04-25,NaN,19.89,서울특별시 성북구 석관동 71-8,까페,3070000,"[서울특별시, 성북구]",0
2061422,블루씨티,영업/정상,2001-05-23,NaN,85.80,서울특별시 은평구 응암동 84-32 지하1층,까페,3110000,"[서울특별시, 은평구]",0
2061469,유토피아 카페,영업/정상,2014-10-30,NaN,167.32,서울특별시 은평구 갈현동 454-3번지 2층,까페,3110000,"[서울특별시, 은평구]",0
2061604,꽃샘,영업/정상,1983-07-19,NaN,20.80,서울특별시 성북구 길음동 1257-2번지,까페,3070000,"[서울특별시, 성북구]",0

In [188]:
#프랜차이즈 변수 확인
franchise = total_cafe_df[(total_cafe_df['사업장명'].str.contains('커피스미스'))]
franchise

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드,시군구,프랜차이즈
43098,커피스미스 천호점,폐업,2018-05-14,2022-05-31,305.00,서울특별시 강동구 천호동 430-13,커피숍,3240000,"[서울특별시, 강동구]",0
52473,커피스미스,폐업,2012-08-23,2013-08-08,144.16,서울특별시 강남구 신사동 662-4번지 지상2층,다방,3220000,"[서울특별시, 강남구]",0
53323,커피스미스 선릉점,폐업,2014-12-12,2016-05-03,137.49,서울특별시 강남구 역삼동 705-23번지 대유타워 지상1층,커피숍,3220000,"[서울특별시, 강남구]",0
169170,커피스미스 등촌역점,폐업,2016-12-16,2017-10-31,63.83,서울특별시 강서구 등촌동 505-7번지 스탠다드호텔 (지상 1층),커피숍,3150000,"[서울특별시, 강서구]",0
172798,커피스미스 노원롯데,폐업,2005-10-20,2015-12-01,115.04,서울특별시 노원구 상계동 713번지 롯데백화점노원점 9층,다방,3100000,"[서울특별시, 노원구]",0
399980,커피스미스 한림대강남성심병원점,영업/정상,2020-09-08,NaN,53.99,서울특별시 영등포구 대림동 964-10,커피숍,3180000,"[서울특별시, 영등포구]",0
468970,커피스미스 노원롯데,영업/정상,2017-03-22,NaN,115.04,서울특별시 노원구 상계동 1414번지,커피숍,3100000,"[서울특별시, 노원구]",0
150364,커피스미스에프씨(주)홍대점,폐업,2011-01-11,2023-04-03,361.25,"서울특별시 마포구 서교동 361-23 1,2층",까페,3130000,"[서울특별시, 마포구]",0
718426,커피스미스 강남수서점,폐업,2014-10-31,2018-11-06,147.65,서울특별시 강남구 자곡동 655-0번지 강남푸르지오시티2차 지상1층 113호,까페,3220000,"[서울특별시, 강남구]",0
732809,커피스미스 코엑스 도심공항몰점,폐업,2014-11-24,2015-07-16,114.16,서울특별시 강남구 삼성동 159-6번지,까페,3220000,"[서울특별시, 강남구]",0
826046,커피스미스 삼청점,폐업,2012-11-20,2016-05-16,NaN,서울특별시 종로구 삼청동 18-1번지 1~3층,까페,3000000,"[서울특별시, 종로구]",0
1001676,커피스미스 이태원점,폐업,2013-10-22,2023-08-24,443.84,서울특별시 용산구 이태원동 172-2 지상2층,까페,3020000,"[서울특별시, 용산구]",0
1008276,커피스미스영등포점,폐업,2013-04-03,2015-04-09,98.48,서울특별시 영등포구 영등포동3가 10-8번지,까페,3180000,"[서울특별시, 영등포구]",0
1034306,커피스미스 이태원해밀턴점,폐업,2014-09-15,2015-02-25,318.00,"서울특별시 용산구 이태원동 127-6번지 2,3,4층",까페,3020000,"[서울특별시, 용산구]",0
1052938,커피스미스 신촌연대점,폐업,2013-04-24,2023-01-02,282.08,"서울특별시 서대문구 창천동 9-21 2,3,4층",까페,3120000,"[서울특별시, 서대문구]",0
1797843,커피스미스 강동첨단단지점,영업/정상,2015-04-24,NaN,165.00,서울특별시 강동구 상일동 502번지,까페,3240000,"[서울특별시, 강동구]",0
1858831,커피스미스 메트로타워점,영업/정상,2015-03-31,NaN,277.10,서울특별시 중구 남대문로5가 537번지 1층,까페,3010000,"[서울특별시, 중구]",0

In [189]:
franchise_total = total_cafe_df[(total_cafe_df['사업장명'].str.contains('이디야')) | (total_cafe_df['사업장명'].str.contains('메가엠지씨')) | (total_cafe_df['사업장명'].str.contains('투썸플레이스')) | (total_cafe_df['사업장명'].str.contains('컴포즈커피')) | (total_cafe_df['사업장명'].str.contains('빽다방')) | (total_cafe_df['사업장명'].str.contains('더벤티')) | (total_cafe_df['사업장명'].str.contains('커피베이')) | (total_cafe_df['사업장명'].str.contains('더벤티'))| (total_cafe_df['사업장명'].str.contains('커피에 반하다')) | (total_cafe_df['사업장명'].str.contains('커피에반하다')) | (total_cafe_df['사업장명'].str.contains('요거프레소')) | (total_cafe_df['사업장명'].str.contains('파스쿠찌')) | (total_cafe_df['사업장명'].str.contains('할리스')) | (total_cafe_df['사업장명'].str.contains('엔제리너스')) | (total_cafe_df['사업장명'].str.contains('디저트39')) | (total_cafe_df['사업장명'].str.contains('디저트 39')) | (total_cafe_df['사업장명'].str.contains('탐앤탐스')) | (total_cafe_df['사업장명'].str.contains('매머드')) | (total_cafe_df['사업장명'].str.contains('감성커피')) | (total_cafe_df['사업장명'].str.contains('달리는커피'))| (total_cafe_df['사업장명'].str.contains('달리는 커피'))| (total_cafe_df['사업장명'].str.contains('카페베네'))| (total_cafe_df['사업장명'].str.contains('셀렉토'))| (total_cafe_df['사업장명'].str.contains('토프레소'))| (total_cafe_df['사업장명'].str.contains('아마스빈'))| (total_cafe_df['사업장명'].str.contains('만랩커피'))| (total_cafe_df['사업장명'].str.contains('더치앤빈 ')) | (total_cafe_df['사업장명'].str.contains('카페게이트')) | (total_cafe_df['사업장명'].str.contains('달콤커피')) | (total_cafe_df['사업장명'].str.contains('커피사피엔스')) | (total_cafe_df['사업장명'].str.contains('커스텀커피'))| (total_cafe_df['사업장명'].str.contains('커피나무 '))| (total_cafe_df['사업장명'].str.contains('커피빈'))| (total_cafe_df['사업장명'].str.contains('스타벅스'))| (total_cafe_df['사업장명'].str.contains('아티제'))| (total_cafe_df['사업장명'].str.contains('폴바셋'))| (total_cafe_df['사업장명'].str.contains('커피스미스'))]
franchise_idx = franchise_total.index
franchise_idx

Index([   1266,    2511,    2649,    3507,    3884,    3980,    4050,    4099,
          4391,    4761,
       ...
       1935322, 1935508, 1937776, 1938554, 1938861, 1942166, 1942169, 1942205,
       1943589, 2000127],
      dtype='int64', length=5701)

In [190]:
#기존 데이터셋에서 프랜차이즈 레코드 삭제 후 franchise 변수를 붙이기
total_cafe_df2 = total_cafe_df.copy()
total_cafe_df2.drop(franchise_idx, inplace=True)
total_cafe_df2

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드,시군구,프랜차이즈
244,텐퍼센트커피(Tenpercent coffee),폐업,2023-09-18,2023-09-25,53.00,서울특별시 노원구 공릉동 567-4,커피숍,3100000,"[서울특별시, 노원구]",0
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000,"[서울특별시, 영등포구]",0
766,트래쉬버스터즈 스낵바,폐업,2023-10-12,2023-10-26,36.00,서울특별시 강남구 대치동 514 SETEC,커피숍,3220000,"[서울특별시, 강남구]",0
1047,카라멜리에오,폐업,2023-10-26,2023-10-31,12.23,서울특별시 강남구 압구정동 429 현대백화점본점,커피숍,3220000,"[서울특별시, 강남구]",0
1091,담은,폐업,2023-09-14,2023-10-24,56.00,서울특별시 강남구 도곡동 419-6,커피숍,3220000,"[서울특별시, 강남구]",0
...,...,...,...,...,...,...,...,...,...,...
2061319,구할 구,영업/정상,1970-10-14,NaN,98.66,서울특별시 중구 남산동2가 24-13 (1층2층),까페,3010000,"[서울특별시, 중구]",0
2061332,갈채,영업/정상,1986-04-25,NaN,19.89,서울특별시 성북구 석관동 71-8,까페,3070000,"[서울특별시, 성북구]",0
2061422,블루씨티,영업/정상,2001-05-23,NaN,85.80,서울특별시 은평구 응암동 84-32 지하1층,까페,3110000,"[서울특별시, 은평구]",0
2061469,유토피아 카페,영업/정상,2014-10-30,NaN,167.32,서울특별시 은평구 갈현동 454-3번지 2층,까페,3110000,"[서울특별시, 은평구]",0
2061604,꽃샘,영업/정상,1983-07-19,NaN,20.80,서울특별시 성북구 길음동 1257-2번지,까페,3070000,"[서울특별시, 성북구]",0

In [191]:
franchise_total['프랜차이즈'] = 1
franchise_total

/var/folders/jc/q2j97l_x5hb7jh99pn7nsbym0000gn/T/ipykernel_75663/1640532418.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  franchise_total['프랜차이즈'] = 1

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드,시군구,프랜차이즈
1266,빽다방 빵연구소 연세대SK국제학사점,폐업,2022-06-21,2023-02-28,186.50,서울특별시 서대문구 신촌동 134 연세대학교,커피숍,3120000,"[서울특별시, 서대문구]",1
2511,달리는커피 강북구청점,폐업,2022-05-02,2023-05-08,38.00,서울특별시 강북구 수유동 188-4 민스빌,커피숍,3080000,"[서울특별시, 강북구]",1
2649,셀렉토커피 북한산두산위브점,폐업,2021-02-01,2023-06-23,49.08,서울특별시 서대문구 홍은동 467 북한산 두산위브,커피숍,3120000,"[서울특별시, 서대문구]",1
3507,이디야 에이스가산포휴점,폐업,2020-12-01,2023-07-11,72.90,서울특별시 금천구 가산동 517-4 에이스 가산 포휴(지식산업센터),커피숍,3170000,"[서울특별시, 금천구]",1
3884,만랩커피 서초법원점,폐업,2020-11-23,2022-10-31,64.80,서울특별시 서초구 서초동 1694-17 경원빌딩 1층 102호,커피숍,3210000,"[서울특별시, 서초구]",1
...,...,...,...,...,...,...,...,...,...,...
1942166,아마스빈 숙대점,영업/정상,2005-02-15,NaN,26.70,서울특별시 용산구 청파동2가 71-127번지 지상1층,까페,3020000,"[서울특별시, 용산구]",1
1942169,(주)보나비 아티제 이대목동점,영업/정상,2011-03-29,NaN,152.50,서울특별시 양천구 목동 911-1 이대목동병원 본관1층,까페,3140000,"[서울특별시, 양천구]",1
1942205,(주)보나비 아티제 이대목동2점,영업/정상,2011-02-15,NaN,8.25,서울특별시 양천구 목동 911-1 이대목동병원 병원동2층,까페,3140000,"[서울특별시, 양천구]",1
1943589,달콤커피한남동점,영업/정상,1999-04-14,NaN,169.60,서울특별시 용산구 한남동 634-14,까페,3020000,"[서울특별시, 용산구]",1
2000127,이디야커피(충무아트점),영업/정상,1996-11-06,NaN,59.49,서울특별시 중구 신당동 249-69번지 1층,까페,3010000,"[서울특별시, 중구]",1

In [192]:
total_cafe_df3 = pd.concat([total_cafe_df2, franchise_total])
total_cafe_df3

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드,시군구,프랜차이즈
244,텐퍼센트커피(Tenpercent coffee),폐업,2023-09-18,2023-09-25,53.00,서울특별시 노원구 공릉동 567-4,커피숍,3100000,"[서울특별시, 노원구]",0
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000,"[서울특별시, 영등포구]",0
766,트래쉬버스터즈 스낵바,폐업,2023-10-12,2023-10-26,36.00,서울특별시 강남구 대치동 514 SETEC,커피숍,3220000,"[서울특별시, 강남구]",0
1047,카라멜리에오,폐업,2023-10-26,2023-10-31,12.23,서울특별시 강남구 압구정동 429 현대백화점본점,커피숍,3220000,"[서울특별시, 강남구]",0
1091,담은,폐업,2023-09-14,2023-10-24,56.00,서울특별시 강남구 도곡동 419-6,커피숍,3220000,"[서울특별시, 강남구]",0
...,...,...,...,...,...,...,...,...,...,...
1942166,아마스빈 숙대점,영업/정상,2005-02-15,NaN,26.70,서울특별시 용산구 청파동2가 71-127번지 지상1층,까페,3020000,"[서울특별시, 용산구]",1
1942169,(주)보나비 아티제 이대목동점,영업/정상,2011-03-29,NaN,152.50,서울특별시 양천구 목동 911-1 이대목동병원 본관1층,까페,3140000,"[서울특별시, 양천구]",1
1942205,(주)보나비 아티제 이대목동2점,영업/정상,2011-02-15,NaN,8.25,서울특별시 양천구 목동 911-1 이대목동병원 병원동2층,까페,3140000,"[서울특별시, 양천구]",1
1943589,달콤커피한남동점,영업/정상,1999-04-14,NaN,169.60,서울특별시 용산구 한남동 634-14,까페,3020000,"[서울특별시, 용산구]",1
2000127,이디야커피(충무아트점),영업/정상,1996-11-06,NaN,59.49,서울특별시 중구 신당동 249-69번지 1층,까페,3010000,"[서울특별시, 중구]",1

### (5)면적변수화 하기
- 면적이 30.0 이하이면 소형(s), 초과하면 일반(l)의 값을 가지는 컬럼 생성

In [202]:
#소형면적 레코드 확인
df_small = total_cafe_df3[total_cafe_df3['소재지면적'] <=30.0]
df_small

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드,시군구,프랜차이즈
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000,"[서울특별시, 영등포구]",0
1047,카라멜리에오,폐업,2023-10-26,2023-10-31,12.23,서울특별시 강남구 압구정동 429 현대백화점본점,커피숍,3220000,"[서울특별시, 강남구]",0
1120,카페올립,폐업,2023-09-19,2023-10-11,18.00,서울특별시 강남구 삼성동 159 코엑스,커피숍,3220000,"[서울특별시, 강남구]",0
1161,카페테리아,폐업,2023-10-20,2023-10-30,27.00,서울특별시 강남구 대치동 514 SETEC,커피숍,3220000,"[서울특별시, 강남구]",0
1294,디오니소스 와인샵,폐업,2022-06-17,2022-09-22,3.30,서울특별시 마포구 연남동 564-25 도화엘리시아,커피숍,3130000,"[서울특별시, 마포구]",0
...,...,...,...,...,...,...,...,...,...,...
1865821,매머드익스프레스선유도점,영업/정상,2014-09-02,NaN,26.00,서울특별시 영등포구 양평동4가 101-3,까페,3180000,"[서울특별시, 영등포구]",1
1935038,매머드익스프레스서울역점,영업/정상,1993-08-06,NaN,28.74,서울특별시 용산구 동자동 11-12 (지상1층),까페,3020000,"[서울특별시, 용산구]",1
1935508,만랩커피 영등포구청점,영업/정상,2012-07-11,NaN,25.45,서울특별시 영등포구 당산동3가 396-11번지,까페,3180000,"[서울특별시, 영등포구]",1
1942166,아마스빈 숙대점,영업/정상,2005-02-15,NaN,26.70,서울특별시 용산구 청파동2가 71-127번지 지상1층,까페,3020000,"[서울특별시, 용산구]",1
1942205,(주)보나비 아티제 이대목동2점,영업/정상,2011-02-15,NaN,8.25,서울특별시 양천구 목동 911-1 이대목동병원 병원동2층,까페,3140000,"[서울특별시, 양천구]",1

In [203]:
#소형면적이면 1, 소형면적이 아니면 0 값을 가진다.
total_cafe_df3['소형면적'] = np.where(total_cafe_df3['소재지면적']<= 30.0, 1, 0)
total_cafe_df3

,사업장명,영업상태명,인허가일자,폐업일자,소재지면적,소재지전체주소,위생업태명,개방자치단체코드,시군구,프랜차이즈,소형면적
244,텐퍼센트커피(Tenpercent coffee),폐업,2023-09-18,2023-09-25,53.00,서울특별시 노원구 공릉동 567-4,커피숍,3100000,"[서울특별시, 노원구]",0,0
331,엔젤리너스커피영등포점,폐업,2023-10-24,2023-10-29,6.60,서울특별시 영등포구 여의도동 84-4 여의도한강공원 이벤트광장,커피숍,3180000,"[서울특별시, 영등포구]",0,1
766,트래쉬버스터즈 스낵바,폐업,2023-10-12,2023-10-26,36.00,서울특별시 강남구 대치동 514 SETEC,커피숍,3220000,"[서울특별시, 강남구]",0,0
1047,카라멜리에오,폐업,2023-10-26,2023-10-31,12.23,서울특별시 강남구 압구정동 429 현대백화점본점,커피숍,3220000,"[서울특별시, 강남구]",0,1
1091,담은,폐업,2023-09-14,2023-10-24,56.00,서울특별시 강남구 도곡동 419-6,커피숍,3220000,"[서울특별시, 강남구]",0,0
...,...,...,...,...,...,...,...,...,...,...,...
1942166,아마스빈 숙대점,영업/정상,2005-02-15,NaN,26.70,서울특별시 용산구 청파동2가 71-127번지 지상1층,까페,3020000,"[서울특별시, 용산구]",1,1
1942169,(주)보나비 아티제 이대목동점,영업/정상,2011-03-29,NaN,152.50,서울특별시 양천구 목동 911-1 이대목동병원 본관1층,까페,3140000,"[서울특별시, 양천구]",1,0
1942205,(주)보나비 아티제 이대목동2점,영업/정상,2011-02-15,NaN,8.25,서울특별시 양천구 목동 911-1 이대목동병원 병원동2층,까페,3140000,"[서울특별시, 양천구]",1,1
1943589,달콤커피한남동점,영업/정상,1999-04-14,NaN,169.60,서울특별시 용산구 한남동 634-14,까페,3020000,"[서울특별시, 용산구]",1,0
2000127,이디야커피(충무아트점),영업/정상,1996-11-06,NaN,59.49,서울특별시 중구 신당동 249-69번지 1층,까페,3010000,"[서울특별시, 중구]",1,0

### (6) 면적변수와 프랜차이즈 변수 합치기
- 면적, 프랜차이즈 변수를 변화시켜 
    - 프랜차이즈 o, 소형면적 o
    - 프랜차이즈 o, 소형면적 x
    - 프랜차이즈 x, 소형면적 o
    - 프랜차이즈 x, 소형면적 x
    <br><br>
으로 변수를 나누기

In [ ]:
# 프랜차이즈 o, 소형면적 o 컬럼 생성

In [ ]:
# 프랜차이즈 o, 소형면적 x 컬럼 생성

### (7) 생존여부, 생존기간, 절단여부 변수 생성하기
    - 생존여부 : 영업상태명으로 판단
    - 생존기간 : 파이썬 라이브러리를 사용하여 일단위 생존기간 변수 생성
    - 절단여부 : 영업상태명으로 판단, 영업/정상이면 우측절단이 발생

### (8) 데이터 내보내기